General:
  Lang: "lang-fr_FR.yml"
# Connection:
#   Host: localhost
#   Port: 3306
#   Database: gmctest
#   User: gmc
#   Password: gmc
#   TablePrefix: GMC_
#   SimultaneousConnection: 4
Connection:
  Host: bol3vp5cj-mysql.services.clever-cloud.com
  Port: 3306
  Database: bol3vp5cj
  User: ulymnspjd93n0dqa
  Password: bGz7GYeLxFPvQXG84Ug
  TablePrefix: GMC_
  SimultaneousConnection: 4
Options:
  # To see auctions that don't have category (button on middle pos 31)
  UncategorizedItems: false
Auctions:
  # Default price for new auctions
  DefaultPrice: 100
  # Use the price of the last similar auction as price of new auction
  UseLastPrice: true
  # An auction expire if it is older than NumberDaysExpiration
  NumberDaysExpiration: 7
  # -1 to ignore purge else specific a number of days to purge database every n days
  PurgeInterval: 30
  MaxAuctionByPlayer : 50
WorldAllowed:
  - world
  - world_the_end
  - world_nether
AllowedLinkBlock:
  - minecraft:ender_chest
  - minecraft:chest
Price:
  Ranges:
    - 1000
    - 100
    - 10
    - 1
    - 0.1
    - 0.01
  Items:
    - minecraft:emerald_block
    - minecraft:emerald
    - minecraft:diamond_block
    - minecraft:diamond
    - minecraft:gold_ingot
    - minecraft:iron_ingot
    - minecraft:coal
    - minecraft:redstone
    - minecraft:dye/4
Interfaces:
  Warn: minecraft:stained_glass_pane/14
  Buttons:
    Background: minecraft:stained_glass_pane/15
    NewAuction: minecraft:nether_star
    CreateAuction: minecraft:nether_star
    BuyAuction: minecraft:nether_star
    RenewAuction: minecraft:wool/1
    UndoAuction: minecraft:wool/14
    RenewEveryAuction: minecraft:wool/1
    UndoEveryAuction: minecraft:wool/14
    ExitButton: minecraft:barrier
    Validate: minecraft:spectral_arrow
    Return: minecraft:tipped_arrow
    CreateShop: minecraft:nether_star
    Money: minecraft:gold_ingot
    GlobalView: minecraft:enchanted_book
    Search: minecraft:hopper
    ViewByCategory: minecraft:compass
    ViewByPlayer: minecraft:chest
    ViewByLastCreated: minecraft:apple
    AuctionSide: minecraft:stained_glass_pane/11
    AuctionMiddle: minecraft:stained_glass_pane
    GlobalShop: minecraft:ender_chest
    AuctionShop: minecraft:purple_shulker_box
    AdminShop: minecraft:chest
    ShopIcon: minecraft:ender_chest
    EditGroupName: minecraft:stained_glass_pane/11
    PreviousPage: minecraft:arrow
    NextPage: minecraft:arrow
    NumPage: minecraft:book
    MaxInOne: minecraft:stained_glass_pane/1
    MaxRepeat: minecraft:stained_glass_pane/1
    InProgressAuction: minecraft:book
    ExpiredAuction: minecraft:book
    SoldAuction: minecraft:book
    BoughtAuction: minecraft:book
    CanceledAuction: minecraft:book
  Circle:
    SetItem: "minecraft:stained_glass_pane/5"
    UnsetItem: "minecraft:stained_glass_pane/11"
Sign:
  Appearance:
    GlobalShop:
      DisplayName: "&a[GlobalShop]"
      DisplayItem: minecraft:compass
      FirstLineToCreate: "globalshop"
    LocalShop:
      DisplayName: '&a[LocalShop]'
      UsePlayerHead: true
      FirstLineToCreate: "localshop"
    AdminShop:
      DisplayName: '&a[AdminShop]'
      DisplayItem: minecraft:end_crystal
      FirstLineToCreate: "adminshop"
    NotWorkingShopDisplayName : "&c[DisableShop]"
