name: Build gmc

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 24
    - name: Build package
      run: mvn clean install -DskipTests=true
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: GlobalMarketChest-${{ github.run_number }}
        path: target/GlobalMarketChest-*.jar
